// ── Static initial business data ──────────────────────────────────────────────
export const INITIAL_BIZ = {
  businessName: "TechVault Pvt Ltd",
  ownerName: "Rahul Sharma",
  businessType: "Private Limited",
  category: "Electronics",
  joinDate: "October 2024",
  bio: "Premium electronics reseller with 5+ years of experience.",
  phone: "+91 87654 32109",
  alternatePhone: "+91 99887 66554",
  website: "www.techvault.in",
  address: {
    line1: "Bandra West",
    line2: "Near Link Road",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    pincode: "400050",
  },
  gst: "27AABCU9603R1ZX",
  pan: "AABCU9603R",
  aadhar: "XXXX-XXXX-1234",
  registrationNumber: "U12345MH2020PTC123456",
  verificationStatus: "Verified",
  isKYCCompleted: true,
  bank: {
    accountHolder: "TechVault Pvt Ltd",
    bankName: "HDFC Bank",
    accountNumber: "XXXXXX1234",
    ifsc: "HDFC0001234",
    upi: "techvault@upi",
  },
  totalListings: 38,
  activeBids: 143,
  totalRevenue: 2840000,
  rating: 4.9,
  reviews: 112,
  successfulTransactions: 120,
  failedTransactions: 3,
  verified: true,
  isApproved: true,
  isPremium: true,
  isBlacklisted: false,
  logo: "",
  banner: "",
};

export const TABS = ["Dashboard", "My Listings", "Analytics", "Payouts", "Settings"];

export const MONTHLY_REVENUE = [
  { month: "Oct", rev: 180000 },
  { month: "Nov", rev: 240000 },
  { month: "Dec", rev: 320000 },
  { month: "Jan", rev: 290000 },
  { month: "Feb", rev: 410000 },
  { month: "Mar", rev: 520000 },
];

export const MAX_REV = Math.max(...MONTHLY_REVENUE.map((m) => m.rev));

// ── Shared card style ─────────────────────────────────────────────────────────
export const card = {
  background: "rgba(255,255,255,.03)",
  border: "1px solid rgba(255,255,255,.07)",
  borderRadius: "16px",
  padding: "20px",
};

// ── Shared style objects ──────────────────────────────────────────────────────
export const styles = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.7)",
    backdropFilter: "blur(6px)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
  },
  modal: {
    background: "#0f172a",
    border: "1px solid rgba(255,255,255,.1)",
    borderRadius: "20px",
    width: "100%",
    maxWidth: "500px",
    maxHeight: "85vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 24px 80px rgba(0,0,0,.6)",
    animation: "modalIn .25s ease",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px 24px 16px",
    borderBottom: "1px solid rgba(255,255,255,.07)",
  },
  modalTitle: { color: "white", fontWeight: 800, fontSize: "18px" },
  closeBtn: {
    background: "rgba(255,255,255,.07)",
    border: "none",
    color: "#94a3b8",
    width: "32px",
    height: "32px",
    borderRadius: "50%",
    cursor: "pointer",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: { padding: "20px 24px", overflowY: "auto", flex: 1 },
  modalFooter: {
    padding: "16px 24px 20px",
    borderTop: "1px solid rgba(255,255,255,.07)",
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
  },
  fieldLabel: {
    color: "#94a3b8",
    fontSize: "11px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: ".05em",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    background: "rgba(255,255,255,.05)",
    border: "1px solid rgba(255,255,255,.1)",
    borderRadius: "10px",
    color: "white",
    fontSize: "14px",
    padding: "10px 14px",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color .2s",
  },
  inputLocked: {
    background: "rgba(255,255,255,.02)",
    color: "#475569",
    cursor: "not-allowed",
    borderColor: "rgba(255,255,255,.05)",
    paddingRight: "36px",
  },
  lockIcon: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: "14px",
    pointerEvents: "none",
  },
  lockedBadge: {
    background: "rgba(99,102,241,.12)",
    color: "#818cf8",
    fontSize: "10px",
    fontWeight: 700,
    padding: "2px 8px",
    borderRadius: "20px",
    border: "1px solid rgba(99,102,241,.2)",
  },
  lockedNote: { color: "#475569", fontSize: "11px", margin: "4px 0 0" },
  cancelBtn: {
    padding: "10px 20px",
    background: "rgba(255,255,255,.06)",
    border: "1px solid rgba(255,255,255,.1)",
    borderRadius: "10px",
    color: "#94a3b8",
    fontWeight: 600,
    fontSize: "14px",
    cursor: "pointer",
  },
  saveBtn: {
    padding: "10px 24px",
    background: "linear-gradient(135deg,#6366f1,#8b5cf6)",
    border: "none",
    borderRadius: "10px",
    color: "white",
    fontWeight: 700,
    fontSize: "14px",
    cursor: "pointer",
    boxShadow: "0 4px 14px rgba(99,102,241,.4)",
  },
  editSectionBtn: {
    padding: "6px 14px",
    background: "rgba(99,102,241,.1)",
    border: "1px solid rgba(99,102,241,.25)",
    borderRadius: "8px",
    color: "#818cf8",
    fontWeight: 600,
    fontSize: "12px",
    cursor: "pointer",
  },
};
